name: flutter_app_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  shared_preferences: ^2.0.7
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bola.jpg
    - assets/futsal1.jpg
    - assets/futsal2.jpg
    - assets/futsal3.jpg
    - assets/lapangan1.jpg
    - assets/lapangan2.jpg


